# Generated by Django 6.0.6 on 2026-06-15 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook')], max_length=20)),
                ('access_token', models.TextField()),
                ('page_access_token', models.TextField(blank=True, help_text='Required for publishing content to Facebook Pages seamlessly', null=True)),
                ('account_id', models.CharField(max_length=255)),
                ('account_name', models.CharField(blank=True, help_text='Name of the connected page or profile', max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
