# Generated by Django 6.0.6 on 2026-06-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='page_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='page_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
