# Generated by Django 6.0.6 on 2026-06-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_socialaccount_page_id_socialaccount_page_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='facebook_followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='facebook_likes',
            field=models.IntegerField(default=0),
        ),
    ]
