# Generated by Django 6.0.6 on 2026-06-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpost',
            name='platform',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
